
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pablo Ezequiel en GitHub
email: http://www.probarnocuestanada.com
description: > # this means to ignore newlines until "baseurl:"
  Comentarios y pruebas sobre distintos proyectos de GitHub
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.probarnocuestanada.com" # the base hostname & protocol for your site
twitter_username: no_cuestanada
github_username:  PabloEzequiel

# Build settings
markdown: kramdown
disqus: pabloeze
google_analytics: UA-80442403-1
title: PabloEzequiel en GitHub


#Disquis
#https://help.disqus.com/customer/en/portal/articles/472138-jekyll-installation-instructions
#comments: true
